modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

issueTrackerURL="https://github.com/JuiceyBeans/Juiceycality/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    # This will be displayed as your mod's logo in the Mods panel.
    # logoFile="icon.png" #optional
    # Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
    # credits="Thanks to Mojang for making this great game" #optional
    # Some more fluff displayed in the Mods panel. Plug your stuff here!
    authors="${mod_author}"
    description = '''
HRT mod that spiraled into a Gregicality: Legacy port
'''

    [[dependencies.${mod_id}]]
        modId = "forge"
        mandatory = true
        versionRange = "[${forge_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[${minecraft_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[${gtceu_version},)"
        ordering = "AFTER"
        side = "BOTH"
